import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Layout Admin Madendev",
    description: "Generated by create next app",
  };

export default function Layout({children}: {children: React.ReactNode}) {
  return (
    <div>{children}</div>
  )
}
