import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Layout Auth Madendev",
    description: "Generated by create next app",
  };


export default function AuthLayout({children}: {children: React.ReactNode}) {
  return (
    <div className='grid grid-cols-2 h-screen'>
        <div>{children}</div>
        <div className='bg-cyan-200 w-full' />
    </div>
  )
}
