import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Layout Auth Madendev",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="grid h-screen grid-cols-1 md:grid-cols-2">
      <div className="flex flex-col items-center justify-center">
        {children}
      </div>
      <div className="h-full w-full bg-amber-100 bg-[url(/mesh-gradient.png')] bg-cover bg-no-repeat" />
    </div>
  );
}
